const classifiche = {
  roundrobin: [
    ['Pos', 'Squadra', 'G', 'V', 'N', 'P', 'GF', 'GS', 'DR', 'PT'],
    ['<!--[if', 'lt IE', '7]>', '<html', 'class="no-js', 'lt-ie9', 'lt-ie8', 'lt-ie7"', 'lang="it-it">', '<![endif]-->'],
    ['var', 'REPROMPT_DELAY =', '1000', '*', '60', '*', '60', '*', '24;', '//24h'],
    ['console.log("FORCE', 'REPROMPT: " +', 'force', '+', '"', '|', 'delay:', '"', '+', 'delay);'],
    ['if', '(lastRequestTimestamp', '>', '0)', "__tcfapi('displayConsentUi',", '2,', 'function', '()', '{', '})'],
    ['if', '(f.fbq)', 'return;', 'n', '=', 'f.fbq', '=', 'function', '()', '{'],
    ['if', '(!f._fbq) f._fbq = n; n.push', '=', 'n;', 'n.loaded', '=', '!0;', 'n.version', '=', "'2.0';"],
    ['<!--', 'Disable Zooming (Chrome and Firefox) Chrome and Firefox on Android will not wait for 300ms if zooming has', 'been', 'disabled', 'using', 'the', 'following', 'viewport', 'setting', '-->'],
    ['var', 's', '=', 'document.createElement("script"),', 'el', '=', 'document.getElementsByTagName("script")[0];', 's.async', '=', 'true;'],
    ['<p', 'Class="browserupgrade">You are using an <strong>outdated</strong> browser. Please', '<a', 'href="http://browsehappy.com/">upgrade', 'your', 'browser</a>', 'to', 'improve', 'your', 'experience.</p>'],
    ['<Button', 'type =', '"button"', 'Class="btn', 'btn', 'btn-icon', 'btn-xs"', 'onclick="WordSearcher.findNext()"><i', 'Class="icon', 'ico-arrow-down"></i></button>'],
    ['<Button', 'type =', '"button"', 'Class="btn', 'btn', 'btn-icon', 'btn-xs"', 'onclick="WordSearcher.findPrev()"><i', 'Class="icon', 'ico-arrow-up"></i></button>'],
    ['<Button', 'type =', '"button"', 'Class="btn', 'btn', 'btn-icon', 'btn-xs"', 'onclick="WordSearcher.closeSearch()"><i', 'Class="icon', 'ico-close"></i></button>'],
    ['<a', 'class="no-league btn btn-link btn-orange"', 'href="https://leghe.fantacalcio.it/registrazione?from=0">Crea', 'una', '<b', 'class="euro">Euro</b>Lega', '<i', 'class="pull-right', 'icon', 'ico-add"></i></a>'],
    ['<a', 'class="no-league btn btn-link btn-blue" href="https://leghe.fantacalcio.it/registrazione?from=1">Unisciti', 'ad', 'una', '<b', 'class="euro">Euro</b>Lega', '<i', 'class="pull-right', 'icon', 'ico-add"></i></a>'],
    ['<a', 'Class="visible-guest btn btn-primary btn-sm btn-raised navbar-btn navbar-right"', 'href="https://leghe.fantacalcio.it/">Vai', 'alle', 'tue', '<span', 'class="euro">Euro</span>Leghe', '<i', 'class="icon', 'fg-right-arrow"></i></a>'],
    ['<a', 'Class="visible-guest-logged btn btn-primary btn-sm btn-raised navbar-btn navbar-right"', 'href="https://leghe.fantacalcio.it/">Vai', 'alle', 'tue', '<span', 'class="euro">Euro</span>Leghe', '<i', 'class="icon', 'fg-right-arrow"></i></a>'],
    ['<!--<button', 'type="button" class="hidden-logged btn', 'btn-primary', 'btn-sm', 'btn-raised', 'navbar-btn', 'navbar-right', 'mw-auto"', 'data-toggle="modal"', 'data-target="#loginModal">Accedi</button>-->'],
    ['<a', 'href="https://leghe.fantacalcio.it/login"', 'Class="hidden-logged', 'btn', 'btn-primary', 'btn-sm', 'btn-raised', 'navbar-btn', 'navbar-right', 'mw-auto">Accedi</a>'],
    ['<a', 'href="https://leghe.fantacalcio.it/riscatta-voucher"', 'Class="hidden-logged', 'btn', 'btn-primary', 'btn-sm', 'navbar-btn', 'navbar-right', 'mw-auto">Riscatta', 'voucher</a>'],
    ['<ul', 'id="leagueMenu" Class="visible-leagues visible-mobile nav', 'navbar', 'navbar-nav', 'navbar-card', 'raised', 'navbar-subheader', 'flex', 'navbar-collapse', 'left-sidenav">'],
    ['<li', 'class="visible-live" data-toggle="tooltip" title="Vai alla pagina del LIVE per visualizzare', 'i', 'voti', 'della', 'tua', 'partita', 'in', 'tempo', 'reale.">'],
    ['data-toggle="tooltip"', 'title="Visualizza e', 'modifica', 'la', 'formazione', 'per', 'la', 'tua', 'prossima', 'partita.">'],
    ['<li', 'data-toggle="tooltip" title="Vai alla', 'pagina', 'degli', 'ultimi', 'risultati', 'calcolati', 'per', 'questa', 'competizione.">'],
    ['<li', 'data-toggle="tooltip"', 'title="Vai', 'alla', 'pagina', 'per', 'partecipare', 'al', 'mercato', 'corrente.">'],
    ['<li', 'data-toggle="tooltip" title="Visualizza la', 'lista', 'dei', 'calciatori', 'ancora', 'liberi', 'della', 'tua', 'Lega.">'],
    ['<li', "class='dropdown-item'><a href='#' data-isin='false' data-id='91513'><span class='competition-icon competition-icon-1'></span>Conference", 'Championship</a></li><li', "class='dropdown-item'><a", "href='#'", "data-isin='true'", "data-id='74346'><span", "class='competition-icon", "competition-icon-1'></span>Conference", 'League</a></li>'],
    ['<a', 'class="no-competition btn', 'btn-link', 'btn-orange"', 'href="https://leghe.fantacalcio.it/lega-degli-eroi--conferences/crea-competizione">Crea', 'Competizione', '<i', 'class="pull-right', 'icon', 'ico-add-user"></i></a>'],
    ['<a', 'class="no-competition', 'btn', 'btn-link"', 'data-toggle="modal"', 'href="#competitionSettingsModal">Riordina', '<i', 'class="pull-right', 'icon', 'fg-cogwheel"></i></a>'],
    ['<div', 'class="main-content', 'col-xs-12', 'col-sm-12', 'col-md-8', 'col-lg-8', 'flex-col', 'flex-start', 'no-padding', 'wait-css-loading">'],
    ['<p>', 'La', 'classifica', 'della', 'competizione', '<em>sempre', 'a', 'portata', 'di', 'mano</em></p>'],
    ['<a', 'id="toexcel"', 'href="javascript:downloadRanking()"', 'class="btn', 'btn-outline', 'pull-right">SCARICA', 'ORA<i', 'class="icon', 'icon-right', 'fg-download"></i></a>'],
    ['document.write', '(document.charset', '?', "'&amp;charset='+document.charset", ':', '(document.characterSet', '?', "'&amp;charset='+document.characterSet", ':', "''));"],
    ['<h5', 'Class="unselectable">Visualizza l\'andamento della classifica', 'in', 'un', 'determinato', 'intervallo', 'di', 'giornate', 'di', 'Lega.</h5>'],
    ['<div', 'Class="slider-label slider-label-light slider-lower', 'mt-2', 'pull-left">da:', '<b>', '<span', 'Class="slider-value"></span>', 'giornata</b>', 'di', 'lega</div>'],
    ['<div', 'Class="slider-label slider-label-light slider-higher', 'mt-2', 'pull-right">a:', '<b>', '<span', 'Class="slider-value"></span>', 'giornata</b>', 'di', 'lega</div>'],
    ['<th', 'data-key="index" Class="sortable', 'cell-index', 'x1', '{{#unless', 'label}}no-smart{{/unless}}">{{#if', 'label}}<div', 'Class="group-label', 'visible-groups">Gruppo', '{{label}}</div>{{/if}}</th>'],
    ['<td', 'data-key="rank-pt"', 'Class="sortable', 'cell-digits-lg', 'cell-secondary', 'x1', 'cell-primary-no-versus', 'hidden-comp-2"><span>{{fix', 'c.p', '0}}</span></td>'],
    ['<div', 'class="team-shirt', 'flex', 'flex-center"><img', 'class="shirt', 'circle"', 'data-src="https://d2lhpso9w1g8dk.cloudfront.net/web/risorse/maglietta_2024/s_{{shirt}}"', 'onerror="handleImageError(this,', 'Settings.missingShirtSrc)"', '/></div>'],
    ['<div', 'class="team-crest', 'flex', 'flex-center"><img', 'class="crest', 'circle"', 'data-src="https://d2lhpso9w1g8dk.cloudfront.net/web/risorse/squadra_2024/{{logo}}"', 'onerror="handleImageError(this,', 'Settings.missingCrestSrc)"', '/></div>'],
    ['<a', 'href="https://leghe.fantacalcio.it/lega-degli-eroi--conferences/squadre" Class="btn', 'btn-sm', 'btn-link">tutte', 'le', 'squadre', '<i', 'class="icon', 'icon-right', 'fg-caret-right"></i></a>'],
    ['<button', 'onclick="RealCalendar.gotoMatchday({{subtract matchday', '1}})"', 'data-dir="prev"', 'Class="prev', 'nav"><i', 'Class="icon', 'ico-down-chevron', 'icon-x2', 'rotate-90cw"></i></button>'],
    ['<button', 'onclick="RealCalendar.gotoMatchday({{sum matchday', '1}})"', 'data-dir="next"', 'Class="next', 'nav"><i', 'Class="icon', 'ico-down-chevron', 'icon-x2', 'rotate-90ccw"></i></button>'],
    ['<a', 'href="https://www.facebook.com/supportoleghe" target="_blank"', 'class="btn', 'btn-blue4', 'btn-block', 'btn-raised', 'btn-sm">Chiedi', 'al', 'supporto', 'leghe</a>'],
    ['<span', 'class="pull-left">© Quadronica s.r.l -', 'P.IVA', '06021941213', '-', 'Tutti', 'i', 'diritti', 'riservati', '-'],
    ['<span', 'class="pull-right"><a target="_blank" href="https://www.fantacalcio.it/privacy">Privacy</a> | <a', 'target="_blank"', 'href="https://www.fantacalcio.it/cookie">Cookie</a>', '|', '<a', 'target="_blank"', 'href="https://www.fantacalcio.it/termini-e-condizioni">Termini', 'e', 'condizioni</a></span>'],
    ['<button', 'type = "button" class="btn btn-facebook btn-raised', 'btn-sm', 'login-facebook"><i', 'class="icon', 'icon-left', 'fg-facebook-logo"></i>', 'Login', 'con', 'facebook</button>'],
    ['<a', 'href = "https://leghe.fantacalcio.it/registrazione?from=0" class="btn', 'btn-raised', 'btn-block', 'btn-sm', 'btn-orange">CREA', 'UNA', '<b', 'class="euro"><br', '/>EURO</b>LEGA</a>'],
    ['<a', 'href = "https://leghe.fantacalcio.it/registrazione?from=1" class="btn btn-raised', 'btn-block', 'btn-sm', 'btn-blue">UNISCITI', 'AD', 'UNA', '<b', 'class="euro"><br', '/>EURO</b>LEGA</a>'],
    ['<p><b>Non', 'hai ricevuto l’email che contiene il link per confermare', 'l’iscrizione?</b>', 'Guarda', 'nella', 'cartella', '"Spam"', 'o', '"Posta', 'indesiderata"</p>'],
    ['<p><b>Non', 'l’hai', 'trovata', 'neppure', 'lì?</b>', 'Allora', 'possiamo', 'reinviartela', 'all’indirizzo', '{{utente.email}}</p>'],
    ['<p>(se', 'l’indirizzo e-mail non è', 'corretto,', 'puoi', 'cambiarlo', 'in', '"<a', 'href="https://leghe.fantacalcio.it/modifica-dati">modifica', 'dati', 'utente</a>")</p>'],
    ['<button', 'class="btn', 'btn-raised', 'btn-small', 'btn-primary"', 'onclick="resendConfirmationEmail(this)">REINVIA', 'L’E-MAIL', 'PER', 'CONFERMARE', 'L’ISCRIZIONE</button>'],
    ['<button', 'type', '=', '"button"', 'class="close"', 'data-dismiss="modal"', 'aria-label="Close"><i', 'class="icon', 'icon-center', 'fg-close"></i></button>'],
    ['<p>', 'Sei sicuro di voler cancellare DEFINITIVAMENTE il tuo utente <span class="brand-title">FANTACALCIO</span>? Cancellando il tuo account, <b>NON POTRAI PIU\' ACCEDERE ALLE TUE', '<span', 'class="euro">EURO</span>LEGHE</b>,', 'né', 'da', 'web,', 'né', 'da', 'app.</p>'],
    ['<button', 'data-dismiss="modal" class="btn btn-raised btn-block btn-sm', 'btn-dark-blue"><i', 'class="icon', 'icon-left', 'ico-remove-small"></i>', 'NO,', 'ci', 'ho', 'ripensato</button>'],
    ['<button', 'id="buttonUnsubscribe" class="btn btn-raised btn-block', 'btn-sm', 'btn-red"><i', 'class="icon', 'icon-left', 'ico-garbage"></i>', 'Sì,', 'voglio', 'cancellarlo</button>'],
    ['<p>Adesso,', 'o successivamente andando in "<a href="https://leghe.fantacalcio.it/modifica-dati">modifica dati utente</a>" puoi decidere di collegare il tuo', 'account', '<span', 'class="brand-title">FANTACALCIO</span>', 'con', 'il', 'tuo', 'account', 'FACEBOOK.</p>'],
    ['<p>Collegando', 'le due cose,', 'potrai', 'effettuare', 'il', 'login', 'con', 'un', 'solo', 'click.</p>'],
    ['<button', 'data-dismiss="modal" class="btn btn-raised btn-block btn-sm', 'btn-dark-blue', 'flex"><i', 'class="icon', 'icon-left', 'ico-remove-small"></i>', 'NON', 'ORA,', 'GRAZIE</button>'],
    ['<button', 'onclick="modalFacebookConnect()" class="btn btn-raised btn-block btn-sm', 'btn-facebook', 'flex"><i', 'class="icon', 'icon-left', 'fg-facebook-logo"></i>', 'CONNETTITI', 'CON', 'FACEBOOK</button>'],
    ['<button', 'type="button" class="btn btn-facebook btn-raised btn-sm', 'icon-center-left"', 'onclick="modalFacebookDisconnect()"><i', 'class="icon', 'fg-facebook-logo"></i>', 'Disconnetti', 'account', 'da', 'facebook</button>'],
    ['<div', 'class="header', '{{header.customClass}}">{{header.label}}', '{{#if', 'header.help}}<a', 'href=""', 'class="btn', 'btn-help"><i', 'class="icon', 'fg-question"></i></a>{{/if}}</div>'],
    ['<div', 'class="edit-modal-row row-{{template}} {{#if accordion}}row-accordion{{/if}} {{rowClass}}', 'separator-{{or', 'separator', "'solid'}}", '{{#if', 'scrollable}}scrollable', 'smart-scrollbar{{/if}}', '{{#if', '_hidden}}hidden{{/if}}">'],
    ['<input', 'class="range-input {{inputClass}}"', 'value="{{@root/_newOne}}"', 'autocomplete="off"', '{{#if', 'readonly}}', 'readonly', '{{/if}}', 'disabled', '/>'],
    ['<input', 'class="range-input {{inputClass}}"', 'value="{{@root/_newOne}}"', 'autocomplete="off"', '{{#if', 'readonly}}', 'readonly', '{{/if}}', 'disabled', '/>'],
    ['autocomplete="off"', '{{#if', '(or', '../readonly', '(lookup', '../disableds', '@index))}}', 'readonly', '{{/if}}', '/>'],
    ['<option', 'value="{{value}}"', '{{#if', 'selected}}', 'selected="selected"', '{{/if}}', '{{#if', 'disabled}}', 'disabled', '{{/if}}>{{label}}</option>'],
    ['<input', 'type="checkbox" class="native" id="{{../key}}_{{@index}}" name="{{../key}}[]" value="{{or', 'value.id', 'value}}"', '{{#if', 'selected}}', 'checked{{/if}}', '{{#if', 'disabled}}', 'disabled{{/if}}>'],
    ['<option', 'value="{{value}}"', '{{#if', '(thereis', 'value', '(lookup', '../.././data', 'groupIndex))}}', 'selected="selected"', '{{/if}}>{{label}}</option>'],
    ['<input', 'type="checkbox" id="{{../key}}_{{@index}}"', 'name="{{../key}}[]"', 'value="{{value}}"', '{{#if', 'selected}}', 'checked{{/if}}', '{{#if', 'disabled}}', 'disabled{{/if}}>'],
    ['<input', 'id="{{key}}{{accordion}}" name="{{key}}" value="{{or accordion \'true\'}}" type="{{#if accordion}}radio{{else}}checkbox{{/if}}"', '{{#if', '(or', 'data', '(getProp', '../_values', 'key))}}', 'checked', '{{/if}}>'],
    ['<span', 'class="togglebutton toggle-status pull-right', '{{#if', 'readonly}}readonly{{/if}}"', 'data-on="{{or', 'labelOn', '\'sì\'}}"', 'data-off="{{or', 'labelOff', '\'no\'}}">'],
    ['<input', 'data-id id="{{key}}_id"', 'name="{{key}}_id"', 'type="hidden"', 'value="{{or', '(lookup', 'value', '3)', '0}}"', '/>'],
    ['<input', 'id="{{key}}_start" name="{{key}}_start" type="text" class="form-control"', 'placeholder="{{#compare', 'type', "'=='", "'time'}}Orario", 'inizio{{else}}Data', 'e', 'ora', 'inizio{{/compare}}"'],
    ['value="{{lookup', 'value', '0}}"', 'readonly', '{{#if', '(or', 'disabled', 'disableStart)}}', 'disabled', '{{/if}}>'],
    ['<input', 'id="{{key}}_end" name="{{key}}_end" type="text" class="form-control"', 'placeholder="{{#compare', 'type', "'=='", "'time'}}Orario", 'fine{{else}}Data', 'e', 'ora', 'fine{{/compare}}"'],
    ['data-field="{{or', 'type \'datetime\'}}" {{#unless freeRange}} data-startend="end" data-startendelem="[name=\'{{key}}_start\']" {{/unless}} value="{{lookup value', '1}}"', 'readonly', '{{#if', '(or', 'disabled', 'disableEnd)}}', 'disabled', '{{/if}}>'],
    ['<a', 'href="#admin" aria-controls="admin" role="tab" data-toggle="tab"><img class="icon"', 'src="https://d2lhpso9w1g8dk.cloudfront.net/web/img/ico_admin.svg"', '/>Area', 'Admin', '<small>LEGA,', 'SQUADRE,', 'MERCATI', 'E', 'COMUNICAZIONI</small></a>'],
    ['var', 'pvar =', '{', 'cid:', '"sky-it",', 'content:', '"0",', 'server:', '"secure-it"', '};'],
  ]
};